### ISSUE TITLE
error: conflicting types for ‘locale_t’

### ISSUE THREAD

**Issue by EvanzEssence** [MiyanoOsu/mgba_miyoo#1]
Getting an error when attempting to compile,

In file included from /home/adminem/mgba_miyoo/src/core/config.c:9:
/home/adminem/mgba_miyoo/include/mgba-util/formatting.h:18:21: error: conflicting types for ‘locale_t’
   18 | typedef const char* locale_t;
      |                     ^~~~~~~~
In file included from /opt/miyoo/arm-buildroot-linux-musleabi/sysroot/usr/include/ctype.h:46,
                 from /home/adminem/mgba_miyoo/include/mgba-util/common.h:23,
                 from /home/adminem/mgba_miyoo/include/mgba/core/config.h:9,
                 from /home/adminem/mgba_miyoo/src/core/config.c:6:
/opt/miyoo/arm-buildroot-linux-musleabi/sysroot/usr/include/bits/alltypes.h:336:34: note: previous declaration of ‘locale_t’ was here
  336 | typedef struct __locale_struct * locale_t;
      |                                  ^~~~~~~~
In file included from /home/adminem/mgba_miyoo/src/core/config.c:9:
/home/adminem/mgba_miyoo/include/mgba-util/formatting.h:24:7: error: conflicting types for ‘strtof_l’
   24 | float strtof_l(const char* restrict str, char** restrict end, locale_t locale);
      |       ^~~~~~~~
In file included from /home/adminem/mgba_miyoo/include/mgba-util/common.h:33,
                 from /home/adminem/mgba_miyoo/include/mgba/core/config.h:9,
                 from /home/adminem/mgba_miyoo/src/core/config.c:6:
/opt/miyoo/arm-buildroot-linux-musleabi/sysroot/usr/include/stdlib.h:158:7: note: previous declaration of ‘strtof_l’ was here
  158 | float strtof_l(const char *__restrict, char **__restrict, struct __locale_struct *);
      |       ^~~~~~~~
make[2]: *** [CMakeFiles/mgba.dir/build.make:118: CMakeFiles/mgba.dir/src/core/config.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:370: CMakeFiles/mgba.dir/all] Error 2
make: *** [Makefile:156: all] Error 2

**Comment by EvanzEssence** [comment]
Nevermind, only available toolchain on github is the "new" version, used docker image with the steward tag and it built, thanks!

**Comment by MiyanoOsu** [comment]
@EvanzEssence  add tag -DHAVE_LOCALE=1 to cflags.
